### ISSUE TITLE
How to remove TypeGPT

### ISSUE THREAD

**Issue by rajvishwakarma1** [olyaiy/TypeGPT#3]
**Is your feature request related to a problem? Please describe.**
After installing TypeGPT i want to remove the application. How do i do it?

**Describe the solution you'd like**
The app was malfunctioning with the system and was slowing it down and I want to remove it.

**Comment by olyaiy** [comment]
hi! 
in order to remove the program, just delete the folder :) its a simple python script and just deleting the folder will be enough :)

Im sorry to hear its causing issues with your system. Would you mind sharing more so i can look into it?

**Comment by rajvishwakarma1** [comment]
Hello,
It crashed multiple times on my OS
OS - MacOS Monterey 12

**Comment by olyaiy** [comment]
Hi, i've released an update. any luck now? Also, did you update your api keys in keys.txt?

**Comment by rajvishwakarma1** [comment]
> Hi, i've released an update. any luck now? Also, did you update your api keys in keys.txt?

Yeah the issues fixed now. (also i have updated my api key in keys.txt
